# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # operating systen for the VM
  config.vm.box = "ubuntu/xenial64"

  # ssh settings
  config.ssh.private_key_path = ["~/.ssh/kubernetesvm_key", "~/.vagrant.d/insecure_private_key"]
  config.ssh.insert_key = false

  # upload public key into the machine
  config.vm.provision "file", source: "~/.ssh/kubernetesvm_key.pub", destination: "~/.ssh/authorized_keys"

  # configure the master node
  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.56.7" #type: "dhcp" 
    master.vm.provision :ansible do |ansible|
      ansible.inventory_path = "../provisioner/hosts"
      ansible.verbose = "vvvv"
      ansible.raw_arguments  = ["--private-key=~/.ssh/kubernetesvm_key"]
      ansible.playbook = "../provisioner/kubernetes.yml"
    end
    master.vm.provision "shell", path: "../provisioner/master.sh" 
  end 
 
  # synchronize folders
  config.vm.synced_folder ".", "/vagrant", :owner => 'vagrant', :mount_options => ["dmode=774", "fmode=774"]
 
  # vm provider
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    #vb.gui = true   

    # Correct this error Stderr: VBoxManage.exe: error: RawFile#0 failed to create the raw output 
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]

    # Group the Machines
    vb.customize ["modifyvm", :id, "--groups", "/Kubernetes Cluster"]

    # Resize Hard Disk
    #vb.customize ["modifymedium", "--resize", "12288"]

    # Customize the number CPUS on the VM:
    vb.cpus = "2"

    # Customize the amount of memory on the VM:
    vb.memory = "2048"
  end
end
